for check
ishimura2387/java-filmorate pull request #6
Opened 2023-12-03 05:00 UTC by ishimura2387

2023-12-04 19:23 UTC, alexache requested changes

2023-12-04 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ArrayList<Film> findAllFilms() {
Лучше использовать интерфейсы вместо конкретных реализаций, то есть  List вместо ArrayList

2023-12-04 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean isValid(Film film) throws ValidationFilmExeption {
Этот метод необязательно делать публичным

2023-12-04 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
А если будет null?

2023-12-04 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return true;
Возвращать true/false выглядит лишним, если в случае ошибок валидации будет исключение

2023-12-04 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().contains(" ")) {
Запутался, зачем и ручная валидация и валидация аннотациями

2023-12-06 07:11 UTC, Ivanov-s-tmn commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
Таких условий лучше избегать по возможности, к примеру, тут из блока if возвращается значение и это значит, что в ветвлении else нет особого смысла, так как код за блоком if будет выполнен только если он не зайдет в условие. Такой код более предпочтительный и легче читается)

2023-12-06 07:11 UTC, Ivanov-s-tmn commented on src/main/java/ru/yandex/practicum/filmorate/exeption/ValidationFilmExeption.java
Свои типы исключений лучше делать непроверяемыми, т.е. наследовать от `RuntimeException`, чтобы не нужно было думать об их выбросе и обработке, потому что как правило, они выбрасываются в нужных нам случаях.
`throws ValidationFilmExeption` и `throws ValidationUserExeption` можно будет убрать из сигнатуры методов

2023-12-06 07:11 UTC, Ivanov-s-tmn commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else {
Тут аналогично, можно избавиться от блока else

2023-12-06 07:11 UTC, Ivanov-s-tmn commented on src/main/java/ru/yandex/practicum/filmorate/annotation/CheckSpaceValidator.java
Отлично реализованы аннотации для валидации!

2023-12-10 04:30 UTC, merged